### ISSUE TITLE
Migrate Payments to Transaction

### ISSUE THREAD

**Issue by jiivan** [golemfactory/clay#4197]
## Rationale
To achieve _Epic Show top-ups and withdraws in the transaction history_ #4172 .

This issue does not cover `Income` nor `DepositPayment`.

### Functional specification
* Implement DB storage as specified in #4172
* Migrate `Payments` to `WalletOperation` and `TaskPayment`. Remove `Payments` table. (use schema migrations)

### User Interface

All rpc that depend on `Payments` should remain the same API (no changes of CLI nor Electron)

### Technical specification
* DB
```
WalletOperation:
    hash: BlockchainTransactionField
    direction: enum(Incoming, Outgoing)
    type: enum(Transfer, DepositTransfer, TaskPayment, DepositPayment)
    status: enum(Awaiting, Sent, Confirmed, Overdue)
    sender_address: [eth address]
    recipient_address: [eth address]
    amount: HexIntegerField
    currency: enum(GNT, ETH)
    gas_cost: HexIntegerField

TaskPayment:
    wallet_operation: ->[WalletOperation 1to1]
    node: str
    task: str
    subtask: str
    paid_amount: HexIntegerField
    expected_amount: HexIntegerField
    accepted_ts: int
    settled_ts: int
```
* Refactor payment RPCs

## Dependencies
None

### Sub-components
None

### Blockers
None

### Additional tests
* Update `Payments` unit tests
* No additional integration tests needed

## QA
_Description of the QA process for the feature_

#### Base test process
_specify one of: ( if unsure, consult @ZmijaWA or @ederenn )_
** QA limited to the single feature (in case of very trivial changes)
** Smoke Test (the limited set of tests designed to ensure that most critical functionality doesn't experience regressions)
** Full Test (full set of tests for the whole application - in case of more extensive application updates, refactoring etc)

### New feature tests
_Add test scenarios for the new feature_

#### Positive Scenario 1
* Step 1
* Step 2
* ...
* Expected results

#### Positive Scenario 2
* ...

#### Negative Scenario 1
* Step 1
* Step 2
* ...
* Some expected problem
* Expected problem handling

### Possible regressions
* is there any functionality that is likely to experience regressions?
* are there any existing application components that should be tested more thoroughly?

### Development
* [ ] Feature implemented
* [ ] Feature unit/integration tests implemented

### Dev QA
* [ ] Basic tests by the developer pass
* [ ] Unit tests pass
* [ ] Golem integration tests pass
* [ ] Concent integration tests pass
* [ ] Concent acceptance tests pass

### QA team
* [ ] Base scenario passes
* [ ] Additional test 1 passes... 
* [ ] ... 

## Issues encountered during QA
_When adding an issue here, please update testing scenarios and QA progress above_
* [ ] link to issue... 
* [ ] ...
